# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"

gem 'rspec', '~> 3.11'

gem 'tty', '~> 0.5.0'

gem 'tty-prompt', '~> 0.6.0'

gem 'rubocop', require: false

gem 'tty-font'

gem 'rainbow', '~> 3.1', '>= 3.1.1'